# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00c747c0109fa4624a11435d7348d11b20eed3de59a0d82a8ca0ef93589a578ac9d6a3b9475db977041f9790df65628875c19c3f2e37291b3e95faa0370fab89

test:
  secret_key_base: d6a8e3fd813aed7a5a1994a882b6bb3648d26a8fd88213d823bae016cea17fce0517ec85d8a34f8bfa7e9d74174e961face68bd9d1d2802b57952ae5ea01fc1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
